# Generated by Django 6.0.4 on 2026-04-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('mobile', models.IntegerField()),
                ('course', models.CharField(max_length=500)),
                ('passing_year', models.CharField(max_length=500)),
            ],
        ),
    ]
