# Generated by Django 6.0.4 on 2026-05-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeTestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='static/user/')),
            ],
        ),
    ]
