# Generated by Django 6.0.4 on 2026-05-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/admin/images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('key_point_1', models.CharField(max_length=255)),
                ('key_point_2', models.CharField(max_length=255)),
                ('key_point_3', models.CharField(max_length=255)),
                ('key_point_4', models.CharField(max_length=255)),
                ('key_point_5', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
