# Generated by Django 6.0.4 on 2026-05-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('review_text', models.TextField()),
                ('review_rating', models.CharField(max_length=10)),
                ('reviewer_position', models.CharField(max_length=100)),
                ('reviewer_image', models.ImageField(blank=True, null=True, upload_to='static/admin/images/')),
            ],
        ),
    ]
