# Generated by Django 6.0.4 on 2026-05-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apanel', '0003_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
