# Generated by Django 6.0.4 on 2026-05-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apanel', '0005_questionpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='marks',
            field=models.IntegerField(default=2),
        ),
    ]
