# Generated by Django 6.0.4 on 2026-05-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apanel', '0006_questionpaper_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='marks',
            field=models.IntegerField(default=''),
        ),
    ]
